### ISSUE TITLE
Web-sivun ulkonäön suunnitelma

### ISSUE THREAD

**Issue by c7paja00** [t7ahaa00/Parkissa-projekti#11]
Suunnitelma, josta selviää nettisivun ulkonäkö

**Comment by lassehav-oamk** [comment]
@t7ahaa00 tämä oli siirretty tuolla projektitaulun puolella "Done", mutta on täällä vielä sulkematta. Jos issuen sulkee täällä issuenäkymässä "close" toiminnolla, niin se siirtyy automaattisesti projektinäkymässä "Done" sarakkeeseen. Tällöin molemmat pysyvät tahdissa.

Sitten on hyvä käyttää esim näitä issueita tallentamaan materiaali. Eli tässä tapauksessa olisi esim linkki käyttöliittymäsuunnitelmaan tai sitten kuvatiedostot suoraan.

**Comment by c7paja00** [comment]
Suunnitelman raaka versio:

[Parkissa.pdf](https://github.com/t7ahaa00/Parkissa-projekti/files/4417430/Parkissa.pdf)
