### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Hunr1** [t7ahaa00/Parkissa-projekti#19]
-Parkkiruutujen tilan muokkaaminen.
-Parkkipaikkojen lisääminen, poistaminen ja muokkaaminen.
-Kameroiden tietojen muokkaaminen (tehdään kun saadaan enemmän tietoa kameroista)
-Käyttäjille Admin/Staff, Käyttäjien lisääminen, poistaaminen ja muokkaaminen. 
-API avainten käyttöönotto.
-Logien päivittäminen ja hakeminen

Low prio
-Vierailijan tietojen lisääminen, poistaminen ja muokkaaminen.
-Vierailijoiden autojen lisääminen,poistaminen muokkaaminen.

(osiot paloiteltu muihin issueihin)

**Comment by lassehav-oamk** [comment]
@Hunr1 tämän tyylinen issue olisi hyvä palastella pieniksi erillisiksi issueiksi. Nyt tämä issue on niin laaja, ettei sitä saa ratkaistua kuin hyvin pitkän ajan kuluttua. Tässä on se ongelma, ettei ole selkeää tietoa siitä milloin esim "Parkkipaikkojen lisääminen, poistaminen ja muokkaaminen" on tehty. Näin suuresta issuesta ei myöskään saa käsitystä mikä sen tilanne on, kuinka suuri osa on tekemättä ja kuinka suuri osa on tehty?

**Comment by lassehav-oamk** [comment]
@Hunr1 toinen hyvä tapa on käyttää labeleita merkitsemään hylätty issue. Helpottaa myöhemmin näiden selaamista, kun näkee suoraan labelista, että tämä on "peruutettu". Label valikosta löytyy valmiiksi esim "invalid" tai sitten voi kirjoittaa oman.
